### ISSUE TITLE
rotation component of `at` isn't bubbled up

### ISSUE THREAD

**Issue by wez** [dvc94ch/pykicad#2]
There are a couple of instances of:

```
                          Tag.parser('at', number, number,
                                    # Bug in some package definitions?
                                    Suppress(Optional(number))) &
```

I'd recommend removing the `Suppress` so that the rotation is bubbled up as an optional 3rd element of the `at` tuple.

**Comment by dvc94ch** [comment]
Can you explain what it's for? Kicad deals with 2D geometry right?

Thanks!

**Comment by dvc94ch** [comment]
Says in the title sorry

**Comment by wez** [comment]
Say you have a rectangular pad; in the footprint editor you can set it to be rotated so that it renders as a diamond rather than a square.  This rotation is stored in the 3rd element of the `at` property.

**Comment by dvc94ch** [comment]
Fixed
