### ISSUE TITLE
Create Travis CI Project

### ISSUE THREAD

**Issue by johnthagen** [dvc94ch/pykicad#25]
Current Travis builds cannot run because the project has not been created on the Travis CI side: 
https://travis-ci.org/dvc94ch/pykicad

**Comment by hmaarrfk** [comment]
It seems that the repo has been deactivated: https://travis-ci.org/dvc94ch/pykicad

@dvc94ch can you fix this?

**Comment by johnthagen** [comment]
[Travis CI (.com) is no longer free for FOSS projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), so closing this issue.
